### ISSUE TITLE
Help needed regarding VsCode externs

### ISSUE THREAD

**Issue by abhi18av** [vshaxe/vscode-extern#12]
Hi Haxe team :)

Actually, this isn't an issue so feel free to close it. I just wanted to ask for your help regarding the basic `js` files you are using to generate the externs.

I need to generate the externs which are compatible with `google closure compiler` and I've found this tool here https://jmmk.github.io/javascript-externs-generator/

However, I'm unable to locate the basic source files to begin with. I know that might be a really n00b question but I would appreciate your help :)

**Comment by Gama11** [comment]
See [vscode.d.ts](https://github.com/Microsoft/vscode/blob/master/src/vs/vscode.d.ts) and [vscode.proposed.d.ts](https://github.com/Microsoft/vscode/blob/master/src/vs/vscode.proposed.d.ts).

The externs in this repo are handwritten btw, not generated.
