### ISSUE TITLE
provide support for showQuickPick that returns array of items for multi-select

### ISSUE THREAD

**Issue by nadako** [vshaxe/vscode-extern#13]
VS Code TS API has a `showQuickPick` method overload that uses literal types in conjunction with type intersections to specify different return type based on whether an option is `true` in an `options` object:

```typescript
function showQuickPick(items: string[] | Thenable<string[]>, options?: QuickPickOptions, token?: CancellationToken): Thenable<string | undefined>;
function showQuickPick(items: string[] | Thenable<string[]>, options: QuickPickOptions & { canPickMany: true; }, token?: CancellationToken): Thenable<string[] | undefined>;
```

This is not representable in Haxe in any way, but we still want to have a proper way to work with multiple selection. Maybe an inline extern function `showQuickPickMany` could be added that sets the `canPickMany` to true and has the array return type.

**Comment by Gama11** [comment]
This might actually be even trickier.. I tried your suggested approach:

```haxe
/**
 * Shows a selection list allowing multiple selections.
 *
 * @param items An array of items, or a promise that resolves to an array of items.
 * @param options Configures the behavior of the selection list.
 * @param token A token that can be used to signal cancellation.
 * @return A promise that resolves to the selected items or `undefined`.
 */
@:extern inline function showQuickPickMany<T:QuickPickItem>(items:EitherType<Array<T>, Thenable<Array<T>>>, ?options:QuickPickOptions, ?token:CancellationToken):Thenable<Null<Array<T>>> {
    if (options == null)
        options = {canPickMany: true};
    else
        options.canPickMany = true;
    return cast showQuickPick(items, options, token);
}
```

For these:

```haxe
window.showQuickPickMany(items);
window.showQuickPick(items);
```

Haxe generates the following code:

```ts
Vscode.window.showQuickPick(items,options,null)
Vscode.window.showQuickPick(items);
```

Note how there are no `null` arguments for optional arguments generated when calling an extern function... Unfortunatenly, VSCode doesn't like a `null` `CancellationToken` at all:

```
Cannot read property 'onCancellationRequested' of null
```

I guess the only solution is `js.Syntax` hackery?

**Comment by Gama11** [comment]
Hm, I guess they handle this via an overload with a default value in VSCode sources:

![](https://i.imgur.com/dGjnS9u.png)

**Comment by Gama11** [comment]
Looks like this works, without `js.Syntax`.. What a mess. :)

```haxe
return cast showQuickPick(items, options, if (token == null) js.Lib.undefined else token);
```

@nadako Should I commit this or can you think of a better option?

**Comment by Gama11** [comment]
Argh, it actually also has on overload with Strings instead of `QuickPickItem` instances, and I don't think inline functions can have overloads yet? :( Maybe we should just return `EitherType<T, Array<T>>` from the regular `showQuickPick()` and call it a day.

**Comment by Gama11** [comment]
I added just the `QuickPickItem` variant for now, `String` items are basically only a subset of that anyway.
