### ISSUE TITLE
StatusBarAlignment enum values are wrong

### ISSUE THREAD

**Issue by Gama11** [vshaxe/vscode-extern#4]
See https://github.com/Microsoft/vscode/blob/66c13c81fd8d844fa2cba38e03bd719e285a1c7e/src/vs/workbench/api/node/extHostTypes.ts#L818 - we're using 0 and 1.

This would be fixed by using `@:enum extern abstract` so there are no constants in the externs at all.

**Comment by Gama11** [comment]
There's a few more `@:enum abstract` types in the codebase, mostly in vscodeProtocol:

![](http://i.imgur.com/s2kmTiJ.png)

**Comment by nadako** [comment]
protocol's are not extern, it's a legit implementation of the specification, codelens is something by simn, and languageclient is a mess anyway, so whatever :)
